### ISSUE TITLE
Nuxt 3 build error Icon.js

### ISSUE THREAD

**Issue by EralKeskinkurt** [antfu/icones#197] opened 2023-08-29 19:35 UTC
### Describe the bug

![errrrrrr](https://github.com/antfu/icones/assets/117297028/2c61a21c-479c-433b-92bf-7050dde979c0)

# i get such error while building nuxt 3 i don't know how to fix it

### Reproduction

----------------

### System Info

```Shell
-------------
```

### Used Package Manager

npm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-04-08 13:50
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-08 13:50 UTC
