### ISSUE TITLE
Workbox fetch error

### ISSUE THREAD

**Issue by TechAkayy** [antfu/icones#79] opened 2022-07-16 08:02 UTC
The icones.js.org site is throwing a workbox fetch error, and sometime the site becomes unresponsive. It use to work fine 3 days ago. Not sure if it's related to the workbox fetch error though. 

![image](https://user-images.githubusercontent.com/73772701/179346132-b8644569-f44a-4943-8208-d0006fc2bfdf.png)

Thank you!

**Comment by TechAkayy** [comment] 2022-07-16 09:23
Did some more research, looks like it's failing for 'clarity' collection - https://icones.js.org/collection/clarity

![image](https://user-images.githubusercontent.com/73772701/179349013-5ed3c3d2-6de3-4b80-b448-f7f84cce3f5a.png)

**Comment by antfu** [comment] 2024-04-08 13:54
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-08 13:54 UTC
