### ISSUE TITLE
Fluent emoji lack antialiasing

### ISSUE THREAD

**Issue by Zombobot1** [antfu/icones#94] opened 2022-09-26 20:12 UTC
### Describe the bug

Many fluent emoji are not scalable because they have visual defects on edges even on top tier displays

Example: medal with dimensions 320x320 converted to png using https://svgtopng.com/
<img width="272" alt="image" src="https://user-images.githubusercontent.com/48030070/192369824-af5ea053-6931-44bd-950a-6e9561129ea7.png">

Same icon on an average display
![image](https://user-images.githubusercontent.com/48030070/192370066-f7a48bfa-2e6c-4c35-b461-8cae40ada85e.png)

Same icon on macbook air display (227 PPI)
<img width="240" alt="image" src="https://user-images.githubusercontent.com/48030070/192370239-0894fbba-35b6-46d6-bc8c-5c048e939eca.png">

### Reproduction

Set width and height to 320 in svg snippet and use svgtopng.com to generate an image

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyberalien** [comment] 2022-10-25 05:34
It is a bug in that renderer.

If you set SVG size to 320x320 and view it in any browser, it renders correctly, unlike PNG generated by that converter. Fluent Emojis have huge number of filters. SVG rendering engines handle them by rasterising image then applying filters to raster image. If scaling is done incorrectly, it results in what you see.

My guess is, it uses some old SVG rendering engine that cannot handle filters properly.

Either way, nothing can be done about that. Rendering bug should be reported to owner of that converter. Overuse of filters is a feature of Fluent Emojis, they are designed that way. If you want emojis without filters, there are also flat versions of same emojis without filters: https://icones.js.org/collection/fluent-emoji-flat

**Comment by Omarov3000** [comment] 2022-10-26 15:30
I'm afraid there has been a misunderstanding. The first example really refers to the converter. I included it for the sake of reproducibility. The actual problem is presented in the other examples. They are screenshots of rendered SVG in chrome on my two monitors. Do you think that it renders correctly?

**Comment by Zombobot1** [comment] 2022-10-26 15:31
I'm afraid there has been a misunderstanding. The first example really refers to the converter. I included it for the sake of reproducibility. The actual problem is presented in the other examples. They are screenshots of rendered SVG in chrome on my two monitors. Do you think that it renders correctly?

**Comment by cyberalien** [comment] 2022-10-26 15:52
Oh, I see. Yes, looks like there are some issues. Blur in original icon from Microsoft repository is not as white as on screenshots and I can confirm that it renders that way on my end too.

**Comment by cyberalien** [comment] 2022-10-26 16:23
Found a bug in tools that optimise icons, running rebuild process now to see result. I suspect both problems are caused by the same bug.

**Comment by cyberalien** [comment] 2022-10-26 16:42
After fix:

<img width="618" alt="Screenshot 2022-10-26 at 19 37 32" src="https://user-images.githubusercontent.com/822287/198084260-17688657-8807-46a8-bb5e-aa9658dea3de.png">

Looks identical to icon in MS repo.

Bug was caused by SVG optimiser that removed attribute in filter it wasn't supposed to remove. There'll be a lot of publishing in next few hours to fix whole chain, but icons have just been fixed in Iconify API and various NPM packages. If you are using one of tools that rely on NPM packages, such as Unplugin Icons or UnoCSS, update dependencies.

**Closed by cyberalien** 2022-10-26 16:42 UTC

**Comment by Zombobot1** [comment] 2022-10-26 18:11
I checked the icon on icones.js.org and it still looks pixelated (i set its size to 256x256)
![image](https://user-images.githubusercontent.com/48030070/198102926-3acda8f5-67e0-4497-a067-b516d7189fe8.png)

This is how the same icon looks in Microsoft repo
![image](https://user-images.githubusercontent.com/48030070/198103242-0599817a-a138-458b-861f-2577f679799a.png)

I guess that it is the old version.

**Comment by Zombobot1** [comment] 2022-10-27 18:28
I see the updated version now. Unfortunately, it still looks bad

![image](https://user-images.githubusercontent.com/48030070/198368294-d82b1df9-5274-4cd8-9c45-63969931e85b.png)

Whereas its fluent emoji counterpart looks decent

![image](https://user-images.githubusercontent.com/48030070/198368650-3598a469-afef-4400-8f9d-c09adefe8be1.png)

Although I am not a designer, I wouldn't allow to use fluent emoji in my projects because they don't look good on average displays.

If you cannot fix the issue could you please give a commentary about it? I think it should help other people make a decision when they are considering this icon pack. Do you think it is acceptable to have such poor antialiasing from designer's point of view?

**Comment by cyberalien** [comment] 2022-10-27 18:42
That's different style of the same icon. Fluent Emoji have 3 styles:
- Default one with lots of filters: https://icones.js.org/collection/fluent-emoji
- Flat without filters: https://icones.js.org/collection/fluent-emoji-flat
- High contrast (monotone): https://icones.js.org/collection/fluent-emoji-high-contrast

In first screenshot icon is from default set, in second screenshot icon is from flat set.

**Comment by Zombobot1** [comment] 2022-10-27 19:09
I understand that they are different icons from different sets.
I want to use the 3d version of fluent icons because they are nice. Hoverwer, I cannot use some of them due to rendering issues. In this case I have to go and copy images from the Microsoft repo.

I think that other people will avoid usage of fluent 3d pack if they know that they have these issues. 

To be honest, I've used many different icons from different sets and they all were ok. Only this pack has untolerable defects.

**Comment by cyberalien** [comment] 2022-10-27 19:16
Yes, I completely agree. Filters are massively overused, rendering those icons causes huge CPU usage spike. I've never seen it so bad anywhere else.

The only solution I can think of is to use PNG. They are designed as 32x32, so render as 64x64 PNG, then use them as 32x32 in documents to make them look smooth on high definition displays. It will render much faster and possibly take less bandwidth.

**Comment by Zombobot1** [comment] 2022-10-27 20:05
Okay, thank you!
