### ISSUE TITLE
Property 'baseURI' does not exist on type 'Window & typeof globalThis'.

### ISSUE THREAD

**Issue by MrHBS** [antfu/icones#40] opened 2021-10-03 12:59 UTC
Anthony how did you manage to get vscode to recognize your types? I keep getting `Property 'baseURI' does not exist on type 'Window & typeof globalThis` even though I have created window.d.ts

**Comment by antfu** [comment] 2024-04-08 13:52
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-08 13:52 UTC
